### ISSUE TITLE
Configure pools of hosts for user groups

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsdockerspawner#4]
```yaml
docker:
  pools:
    internal:
      users: [ a, b, c]
      hosts: [ h, i, j ]
      servers_per_host: 1
      cpus_per_server: 20
      gigabytes_per_server: 60
   default:
      hosts: [ q, r, s ]
      servers_per_host: 5
      cpus_per_server: 4
      gigabytes_per_server: 10
```
